@startuml
interface PersonService{
+ delete(id: Integer): void
}

class PersonServiceBean{
+ delete(id: Integer): void
}

PersonService <|.. PersonServiceBean: 实现

note bottom of PersonService: 或者 class PersonServiceBean implements PersonService{}

@enduml